"""validator が使う静的契約値。"""

QUEUE_TEMPLATE_PATHS = (
    "template/.agents/orchestra/queue/templates/sage_assignment.yaml",
    "template/.agents/orchestra/queue/templates/sage_report.yaml",
    "template/.agents/orchestra/queue/templates/adventurer_assignment.yaml",
    "template/.agents/orchestra/queue/templates/adventurer_report.yaml",
    "template/.agents/orchestra/queue/templates/adventurer_inbox.yaml",
    "template/.agents/orchestra/queue/templates/cartographer_assignment.yaml",
    "template/.agents/orchestra/queue/templates/cartographer_report.yaml",
    "template/.agents/orchestra/queue/templates/examiner_assignment.yaml",
    "template/.agents/orchestra/queue/templates/examiner_report.yaml",
    "template/.agents/orchestra/queue/templates/inquisitor_trial.yaml",
    "template/.agents/orchestra/queue/templates/inquisitor_report.yaml",
    "template/.agents/orchestra/queue/templates/warden_assignment.yaml",
    "template/.agents/orchestra/queue/templates/role_inbox.yaml",
    "template/.agents/orchestra/queue/templates/request.yaml",
    "template/.agents/orchestra/queue/templates/command.yaml",
)

REQUIRED_PATHS = [
    ".dockerignore",
    "Dockerfile",
    "Makefile",
    "README.md",
    "VERSION",
    "compose.yaml",
    "requirements.txt",
    "docs/orchestration-runtime.md",
    "docs/agent-deployment.md",
    "docs/guild-quest-lifecycle.md",
    "docs/customization.md",
    "docs/quest-awareness-runtime.md",
    "docs/agent-memory.md",
    "docs/deployment-patterns.md",
    "docs/claude-compatibility.md",
    "docs/prompt-recipes.md",
    "docs/localization-management.md",
    "template/AGENTS.md",
    "template/.agents/orchestra/docker/.dockerignore",
    "template/.agents/orchestra/docker/Dockerfile",
    "template/.agents/orchestra/docker/requirements.txt",
    "template/.codex/config.toml",
    "template/.codex/hooks.json",
    "template/.codex/hooks/stop_quality_gate.py",
    "template/.codex/hooks/stop_quality_gate.sh",
    "template/.codex/agents/adventurer.toml",
    "template/.codex/agents/sage.toml",
    "template/.codex/agents/cartographer.toml",
    "template/.codex/agents/courier.toml",
    "template/.codex/agents/examiner.toml",
    "template/.codex/agents/guildmaster.toml",
    "template/.codex/agents/inquisitor.toml",
    "template/.codex/agents/artificer.toml",
    "template/.codex/agents/warden.toml",
    "template/.codex/agents/captain.toml",
    "template/.agents/orchestra/config/settings.yaml",
    "template/.agents/orchestra/README.md",
    "template/.agents/orchestra/docs/agent-memory.md",
    "template/.agents/orchestra/instructions/common.md",
    "template/.agents/orchestra/instructions/sage.md",
    "template/.agents/orchestra/instructions/cartographer.md",
    "template/.agents/orchestra/instructions/examiner.md",
    "template/.agents/orchestra/instructions/guildmaster.md",
    "template/.agents/orchestra/instructions/captain.md",
    "template/.agents/orchestra/instructions/warden.md",
    "template/.agents/orchestra/instructions/adventurer.md",
    "template/.agents/orchestra/instructions/inquisitor.md",
    "template/.agents/orchestra/instructions/artificer.md",
    "template/.agents/orchestra/instructions/session_recovery.md",
    "template/.agents/orchestra/logs/daily/README.md",
    "template/.agents/orchestra/queue/README.md",
    *QUEUE_TEMPLATE_PATHS,
    "template/.agents/skills/repository-design-mapmaking/SKILL.md",
    "template/.agents/skills/quest-awareness-loop/SKILL.md",
    "template/.agents/skills/use-guild-workflow/SKILL.md",
    "template/.agents/orchestra/scripts/inbox_write.sh",
    "template/.agents/orchestra/scripts/docker_python.sh",
    "template/.agents/orchestra/scripts/claude_compat.py",
    "template/.agents/orchestra/scripts/queue_db.py",
    "template/.agents/orchestra/scripts/queue_audit.py",
    "template/.agents/orchestra/scripts/queue_schema.sql",
    "template/.agents/orchestra/scripts/snapshot_digest.py",
    "scripts/install.py",
    "scripts/model_selection_eval.py",
    "scripts/model_selection_eval.yaml",
    "scripts/root_orchestration_eval.py",
    "scripts/root_orchestration_eval.yaml",
    "scripts/validation/model_selection.py",
    "scripts/validation/root_orchestration.py",
    "scripts/validation/snapshot_digest.py",
    "scripts/validation/golden_quests.py",
    "scripts/validation/fixtures/golden_quests/sage_dialogue_same_focus_stop.yaml",
    "scripts/validation/fixtures/golden_quests/focused_trial_risk_triggered_review.yaml",
    "scripts/validation/fixtures/golden_quests/ledger_injection_negative.yaml",
    "scripts/validation/fixtures/golden_quests/mapmaking_readonly_no_edit.yaml",
    "scripts/validation/fixtures/golden_quests/root_coordination_only.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_blocked_contract.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_unverified_outcome.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_contradictory_evidence.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_failed_check.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_memory_prevention_artifact.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_scope_drift.yaml",
    "scripts/validation/fixtures/golden_quests/evidence_state_security_trigger.yaml",
    "scripts/validation/fixtures/golden_quests/warden_evidence_trigger.yaml",
    "scripts/validation/fixtures/golden_quests/safety_gate_needs_human.yaml",
    "scripts/validation/fixtures/golden_quests/solo_small_fix_no_git.yaml",
    "scripts/clean_install.sh",
    "scripts/docker_python.sh",
    "scripts/install.sh",
    "scripts/sync.sh",
]

QUEST_RANKS = {"mapmaking", "errand", "solo_quest", "party_quest", "guild_quest"}
TRIAL_DEPTHS = {"none", "self_check", "peer_review", "focused_trial", "multi_focus_trial", "safety_gate"}
# Compact, evidence-based state carried between owners.  Unlike the retired
# quest-awareness scorecard this contains only facts that can change control
# flow.  Numeric self-confidence is deliberately not part of the contract.
EVIDENCE_STATE_KEYS = {
    "blocking_unknowns",
    "failed_checks",
    "scope_drift",
    "high_risk_triggers",
    "verification_status",
    "next_action",
    "stop_reason",
}

CORE_TRIAL_CHECKS = {
    "success_criteria",
    "authority_boundary",
    "scope_boundary",
    "safety_items",
    "validation_evidence",
    "regression_risk",
}
OPERATIONS = {"append", "update", "replace", "mark_completed"}
ARTIFACT_REQUIRED_FIELDS = ["artifact_type", "schema_version", "workflow_id", "structured_data_usage"]
STRUCTURED_DATA_USAGE_FIELDS = ["structured_inputs", "decision_rationale", "evidence_refs"]
EVENT_INPUT_REQUIRED_FIELDS = [
    "event_id",
    "timestamp",
    "actor",
    "event_type",
    "entity",
    "operation",
    "workflow_id",
    "structured_data_usage",
    "payload",
    "event_safety",
]
EVENT_SAFETY_FIELDS = ["safety_items", "human_confirmation_required"]
AUTHORITY_KEYS = {"read", "edit", "validate", "local_git", "external_actions"}
LEDGER_TABLES = {
    "queue_metadata",
    "events",
    "quests",
    "requests",
    "commands",
    "assignments",
    "reports",
    "trials",
    "inbox_messages",
}
EVENT_TYPES = {
    "quest_created",
    "quest_updated",
    "quest_completed",
    "request_enqueued",
    "command_created",
    "assignment_created",
    "assignment_updated",
    "report_recorded",
    "trial_recorded",
    "inbox_message_added",
    "status_changed",
    "dashboard_updated",
    "state_compacted",
}
ENTITY_TYPES = {
    "quest",
    "request",
    "command",
    "assignment",
    "report",
    "trial",
    "message",
    "dashboard",
    "state",
    "status",
}
EVENT_ENTITY_TYPE_RULES = {
    "quest_created": {"quest"},
    "quest_updated": {"quest"},
    "quest_completed": {"quest"},
    "request_enqueued": {"request"},
    "command_created": {"command"},
    "assignment_created": {"assignment"},
    "assignment_updated": {"assignment"},
    "report_recorded": {"report"},
    "trial_recorded": {"trial", "report"},
    "inbox_message_added": {"message"},
    "status_changed": {"status"},
    "dashboard_updated": {"dashboard"},
    "state_compacted": {"state"},
}
VOCABULARY_DRIFT_TERMS = (
    "task_id",
    "quest_queue",
    "adventurer_task.yaml",
    "inquisitor_task.yaml",
    "docs/agent-expansion-by-scale.md",
)
ACTIVE_PROSE_PATHS = (
    "README.md",
    "docs/agent-deployment.md",
    "docs/agent-memory.md",
    "docs/customization.md",
    "docs/deployment-patterns.md",
    "docs/claude-compatibility.md",
    "docs/guild-quest-lifecycle.md",
    "docs/localization-management.md",
    "docs/orchestration-runtime.md",
    "docs/prompt-recipes.md",
    "docs/quest-awareness-runtime.md",
    "docs/use-cases/README.md",
    "docs/use-cases/01-mapmaking-before-implementation.md",
    "docs/use-cases/02-small-fix-solo-quest.md",
    "docs/use-cases/03-party-quest-cross-cutting-change.md",
    "docs/use-cases/04-focused-trial-after-implementation.md",
    "docs/use-cases/05-safety-escalation.md",
    "docs/use-cases/06-ledger-and-local-git.md",
    "docs/use-cases/07-claude-context.md",
    "docs/use-cases/08-guild-quest-strategy-and-parties.md",
    "docs/use-cases/09-warden-control-loop.md",
    "docs/use-cases/10-sage-owner-synthesis.md",
    "scripts/install.py",
    "template/AGENTS.md",
    "template/.codex/config.toml",
    "template/.codex/agents/adventurer.toml",
    "template/.codex/agents/sage.toml",
    "template/.codex/agents/cartographer.toml",
    "template/.codex/agents/courier.toml",
    "template/.codex/agents/examiner.toml",
    "template/.codex/agents/guildmaster.toml",
    "template/.codex/agents/inquisitor.toml",
    "template/.codex/agents/artificer.toml",
    "template/.codex/agents/warden.toml",
    "template/.codex/agents/captain.toml",
    "template/.agents/orchestra/README.md",
    "template/.agents/orchestra/config/settings.yaml",
    "template/.agents/orchestra/dashboard.md",
    "template/.agents/orchestra/docs/agent-memory.md",
    "template/.agents/orchestra/queue/README.md",
    "template/.agents/orchestra/instructions/adventurer.md",
    "template/.agents/orchestra/instructions/sage.md",
    "template/.agents/orchestra/instructions/cartographer.md",
    "template/.agents/orchestra/instructions/common.md",
    "template/.agents/orchestra/instructions/examiner.md",
    "template/.agents/orchestra/instructions/guildmaster.md",
    "template/.agents/orchestra/instructions/inquisitor.md",
    "template/.agents/orchestra/instructions/artificer.md",
    "template/.agents/orchestra/instructions/captain.md",
    "template/.agents/orchestra/instructions/warden.md",
    "template/.agents/orchestra/instructions/session_recovery.md",
    "template/.agents/orchestra/logs/daily/README.md",
)
ACTIVE_PROSE_DRIFT_TERMS = (
    "メタ認" "知",
    "固定 route",
    "規模別 route",
    "軽量 assignment",
    "agent の自律性",
    "専用 agent",
    "`courier` agent",
    "runtime contract/state",
    "runtime state として",
    "動的 state",
    "role instruction",
    "golden task",
)
